from .user import User
from .student import Student
from .academia import Academician
from .company import Company
from .skill import Skill
from .student_skill import StudentSkill
from .opportunity import Opportunity
from .opportunity_skill import OpportunitySkill
from .application import Application
from .collaboration import Collaboration
from .placement import Placement
from .project import Project
from .certification import Certification
from .achievement import Achievement
from .learning_resource import LearningResource
from .student_learning import StudentLearning